### ISSUE TITLE
BUG SQUASHING

### ISSUE THREAD

**Issue by mulshine** [spiricom/MantaMate#85] opened 2017-07-22 22:23 UTC
- [x] [SQUASHED] Switching to saved preset: trigger/gates are all funky
- [x]  [SQUASHED] Keyboard mode, turn off BR button LED
- [x]  [SQUASHED] Keyboard mode arp patterns crash (3 and 7 , maybe more? )

**Comment by JoshuaStorm** [comment] 2017-07-23 17:24
- [x] [TRIPLE SQUASHED] Setting second sequencer page to trigger mode doesn't seem to do anything. Doing double trigger mode is kinda confusing in general

Edit: Correction, it DOES update the UI, and you can use the UI like you would with the first page, but it doesn't seem to output triggers

**Comment by JoshuaStorm** [comment] 2017-07-23 19:42
- [x] [SQUASHED] I'm stilling getting an issue where triggers are weak when reloading presets after a hard restart
- [x] [NOT A BUG - that's touch/arpeggiator in keyboard mode, because we decided not to allow split keyboard mode for now] When on keyboard mode, the Split Mode Toggle hex moves down one row for some reason

**Comment by JoshuaStorm** [comment] 2017-07-23 20:08
- [x]  [SQUASHED] Minor: Hold left option menu, switch to Keyboard mode, switch to Direct mode. While you still hold the option menu, it seems like the second to bottom level of LEDs doesn't clear from the Keyboard menu. Could be confusing

**Comment by JoshuaStorm** [comment] 2017-07-23 20:11
- [x] [SQUASHED] Go to left menu and setup like this: (Direct mode, second row, second hex the rest doesn't matter)![image](https://user-images.githubusercontent.com/12414183/28502486-f6f71d7e-6fb8-11e7-8f52-d6d078bb6097.png)

Then try going to keyboard mode. It gets in some weird state

**Comment by JoshuaStorm** [comment] 2017-07-26 00:19
- [x] [SQUASHED af] Restart MantaMate, switch to trigger mode. Add a hex or two. Switch to Edit Mode. Edit a hex. Notice you end up in some weird state.   (Jeff adding to this: seems like the weird behavior starts when you hit a third hexagon to edit)

**Comment by JoshuaStorm** [comment] 2017-07-28 00:59
- [x] [UNINTENDED DOUBLE SQUASHED] This may be intended and I'm just not used to it. If you set a hex to be a rest and then select a note value, it stays a rest. It does become the selected note when you deselect the rest. I think this works okay as intended functionality if that is what we want, but we should emphasize that it is a rest _toggle_ if that is the case
   -Jeff note - I think it's not desirable behavior.

**Comment by JoshuaStorm** [comment] 2017-07-28 01:08
- [x] [thoroughly muddled] Go to keyboard mode, select more than 1 voice, trigger multiple voices. Go back to 1 voice. The 1V/O outputs from the other voices stay high. Not a huge deal but I imagine this is an easy bug to smash

**Comment by JoshuaStorm** [comment] 2017-07-28 01:11
- [x] I somehow got the keyboard mode in a weird state where it won't let me leave 4 voice mode... The UI changes but I'm definitely stuck in 4 voice mode. Also the arp mode stops triggering, unsure if that's related. Will edit this comment if I identify how I got into this state

MIKE: @JoshuaStorm I can't isolate the bug. If either of you experience this again let me know. 

Could never replicate

**Comment by JoshuaStorm** [comment] 2017-07-28 01:14
- [x] Keyboard mode: 1 voice mode, putting a finger on second hex causes output A2 to do some nonsense.

Similarly, 2 voice mode causes weirdness on A2 as well, which is actually a big issue because it's changing the 1V/O of the 2nd voice

3 voice mode causes weirdness on A3.

4 voice mode causes weirdness on A4

JEFF: I don't see this. What's weird? In mono mode, we have room for an extra trigger so I stuck one on A2. In the other modes, this trigger goes away, and I don't see anything strange happening on those other A's. Mike, do you see it?

re Jeff:
JOSH: Ah yeah, for 1 voice that seems fine. I still get some weirdness on 2-4 when pressing an extra key though.

@Josh - I still don't see it -- the last voice always gets stolen if you add a new key, maybe that's what you're hearing?

@spiricom @JoshuaStorm MIKE: josh, in mono keyboard, A2 is a trigger output. maybe thats whats confusing?

**Comment by JoshuaStorm** [comment] 2017-07-28 01:15
- [x] [squished/oozing] Go to keyboard mode, select 2, 3, or 4 voice mode. Then go to Direct! mode. Notice it seems to go into Direct! mode but the Direct! mode LED stays amber and the keyboard mode LED stays red

**Comment by JoshuaStorm** [comment] 2017-07-28 01:24
- [x] [smoshed] When in Direct! mode 1 (where only half the outputs are used), the top two option buttons are red. When in Direct! mode 2 (where all 12 outputs are used), they aren't red. Just a bit confusing as a user

**Comment by JoshuaStorm** [comment] 2017-07-28 01:30
- [x] [smished] Go to split sequencer mode. Set one of them as a trigger and one as a pitched sequencer. If you're focused on a trigger sequencer step and then hit any of the upper hexes that AREN'T associated with the triggers, the UI changes to a pitched sequencer. Could cause confusion

**Comment by JoshuaStorm** [comment] 2017-07-28 01:34
- [x] Go to split mode. Set one to a sequencer, another to a keyboard. Two bugs:

- (This may be intentional?) The keyboard covers the entire UI, but the sequencer still updates the UI so it gets in this weird overlay state.
-  Going to two voice keyboard mode while split stops your sequence when you should be able to have a two-voice keyboard and a sequencer simultaneously 

Not bugs anymore because we arent implement split mode!

**Comment by JoshuaStorm** [comment] 2017-07-28 01:36
- [x] [minor smish] Minor UI bug: Trigger mode, when you turn on the mute then turn it back off with a hex selected, it doesn't update the UI back to the state of the hex you have highlighted

**Comment by JoshuaStorm** [comment] 2017-07-28 01:38
- [x] [smooked on account of being not an implementation goal] Split mode, one sequencer, one Direct!/keyboard mode. Set your "page" to the sequencer, you still get the UI for the Direct! mode options. Even worse: if you hit the Edit layout button thingy (the middle-ish red one) you get in this odd state where you are editing UI and seemingly stuck! (you can escape by hitting though)

**Comment by JoshuaStorm** [comment] 2017-07-28 01:40
- [x] [acorn squash] Minor UI bug: Go to right option menu. Hit a lower hex so it turns amber. Then hit the bottom left red hex. Then hit another different lower hex. You now have two amber hexes when I believe only 1 should be amber.

**Comment by JoshuaStorm** [comment] 2017-07-28 01:46
- [x] [pretty squashed but could use some more trigger mode testing!] When on non-split mode, setting both sequencers to trigger mode, we should be able to see all 8 trigger thingies but initially it doesn't show them until you press all of them

MIKE: hmm not sure about this one. I think if it's Full with two Trigger Sequencers, the user should only see the Triggers relative to the current page/sequencer, right? If we are Split with two Trigger Sequencers, then I'd expect to be able to see both Trigger panels at once. Thoughts?

JEFF: I agree with Mike - only show one trigger panel when in full mode

**Comment by JoshuaStorm** [comment] 2017-07-28 02:07
All I could find today. I can do another bug finding session + manual writing on Saturday

I didn't test the first two preference menus much

(Jeff sez:  Thanks, Man!  You da best)

**Comment by mulshine** [comment] 2017-07-28 16:09
sweet thanks josh! trying to hit all these now - once this windows update
happens -_-

**Comment by mulshine** [comment] 2017-07-28 21:14
Let me know when you find more @JoshuaStorm  @spiricom !

**Comment by spiricom** [comment] 2017-07-28 21:34
Yeah! Will do

**Comment by JoshuaStorm** [comment] 2017-07-29 17:47
This was marked as squashed, but I still seem to get this issue in dev :(

- [x] [pretty sure its squashed now, check it out @JoshuaStorm @spiricom] Restart MantaMate, switch to trigger mode. Add a hex or two. Switch to Edit Mode. Edit a hex. Notice you end up in some weird state. (Jeff adding to this: seems like the weird behavior starts when you hit a third hexagon to edit)

JEFF: yeah, I think it has to do with hitting hex 0. That seems to start the weirdness.

**Comment by spiricom** [comment] 2017-07-29 19:44
- [x]  [smudged] When going from preset 2 to preset 1 with a Manta, the numVoices parameter doesn't properly set for monophonic operation, and the 2nd voice remains active.

**Comment by JoshuaStorm** [comment] 2017-07-29 21:57
- [x] [zuchinni] Set to keyboard mode, go to Right option menu. It only has two on the second top row, isn't it supposed to have a bunch of options for arp patterns?

MIKE: @JoshuaStorm  yes youre right i introduced that bug! smoshed it tho

**Comment by spiricom** [comment] 2017-07-30 01:23
- [x] [butternut] deviate sequencer button is not lit up amber

**Closed as completed** 2017-10-20 16:47 UTC
